name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: PixelifySans
      fonts:
        - asset: font/Pixelify_Sans/static/PixelifySans-Regular.ttf
        - asset: font/Pixelify_Sans/static/PixelifySans-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - img/
    - video/